version: "3.9"

services:
  backend:
    build: .
    container_name: jobby-backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    container_name: jobby-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/jobby-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
