"""init job_applications

Revision ID: 55cd43edfa58
Revises: 
Create Date: 2025-10-24 12:03:05.596575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55cd43edfa58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('role_title', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('apply_url', sa.String(length=500), nullable=True),
    sa.Column('stage', sa.Enum('APPLIED', 'UNDER_REVIEW', 'OA', 'INTERVIEW', 'OFFER', name='jobstage', native_enum=False, length=32), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'REJECTED', 'OFFER_ACCEPTED', 'WITHDRAWN', name='jobdecision', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_id'), 'job_applications', ['id'], unique=False)
    op.create_index('ix_job_apps_decision', 'job_applications', ['decision'], unique=False)
    op.create_index('ix_job_apps_last_status_at_desc', 'job_applications', ['last_status_at'], unique=False)
    op.create_index('ix_job_apps_stage', 'job_applications', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_apps_stage', table_name='job_applications')
    op.drop_index('ix_job_apps_last_status_at_desc', table_name='job_applications')
    op.drop_index('ix_job_apps_decision', table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_id'), table_name='job_applications')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
